<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5ddeb180862d4',
        'title' => 'Publish on sociala media',
        'fields' => array(
            array(
                'key' => 'field_5de3a0d2f9ad5',
                'label' => 'Missing webhooks',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Add the catch webhooks for your LinkedIn-, Facebook-, and/or Twitter-zaps in the <a href="/wp-admin/options-general.php?page=kntnt-schedule-sociala-media-zapier">settings page</a>.',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
                'wpml_cf_preferences' => 0,
            ),
            array(
                'key' => 'field_5ddec09314fa4',
                'label' => 'LinkedIn',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wp-typography' => 'none',
                'placement' => 'top',
                'endpoint' => 0,
                'wpml_cf_preferences' => 0,
            ),
            array(
                'key' => 'field_5de16074d18f0',
                'label' => 'Scheduled LinkedIn posts',
                'name' => 'linkedin_posts',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wpml_cf_preferences' => 0,
                'wp-typography' => 'none',
                'collapsed' => 'field_5de16074d18f3',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add LinkedIn post',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5de16074d18f1',
                        'label' => 'Post the excerpt?',
                        'name' => 'publish_excerpt',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                    ),
                    array(
                        'key' => 'field_5de16074d18f2',
                        'label' => 'When should the post be published?',
                        'name' => 'date_and_time',
                        'type' => 'date_time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'display_format' => 'Y-m-d H:i',
                        'return_format' => 'Y-m-d H:i',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_5de16074d18f3',
                        'label' => 'Post',
                        'name' => 'content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5de16074d18f1',
                                    'operator' => '!=',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 2,
                        'wp-typography' => 'none',
                        'default_value' => '',
                        'placeholder' => 'The excerpt of the article will be posted if this field is left empty.',
                        'maxlength' => 700,
                        'rows' => 3,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5de16074d18f4',
                        'label' => '',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'message' => 'The post is published shortly after the set time. If no time is specified and the article is already published, the post is published shortly after the article is updated. If no time is specified and the article is a draft or scheduled for publication, the content is published shortly after the article is published. If the article isn\'t published or isn\'t public at the time of publishing the post, the post is never published.',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_5ddec0a714fa6',
                'label' => 'Facebook',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wpml_cf_preferences' => 0,
                'wp-typography' => 'none',
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5de161425d142',
                'label' => 'Scheduled Facebook posts',
                'name' => 'facebook_posts',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wpml_cf_preferences' => 0,
                'wp-typography' => 'none',
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Facebook post',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5de161425d143',
                        'label' => 'Post the excerpt?',
                        'name' => 'post_excerpt',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                    ),
                    array(
                        'key' => 'field_5de161425d144',
                        'label' => 'When should the post be published?',
                        'name' => 'date_and_time',
                        'type' => 'date_time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'display_format' => 'Y-m-d H:i',
                        'return_format' => 'Y-m-d H:i',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_5de161425d145',
                        'label' => 'Post',
                        'name' => 'content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5de161425d143',
                                    'operator' => '!=',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 2,
                        'wp-typography' => 'none',
                        'default_value' => '',
                        'placeholder' => 'The excerpt of the article will be posted if this field is left empty.',
                        'maxlength' => 63206,
                        'rows' => 3,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5de161425d146',
                        'label' => '',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'message' => 'The post is published shortly after the set time. If no time is specified and the article is already published, the post is published shortly after the article is updated. If no time is specified and the article is a draft or scheduled for publication, the content is published shortly after the article is published. If the article isn\'t published or isn\'t public at the time of publishing the post, the post is never published.',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_5ddec0a614fa5',
                'label' => 'Twitter',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wp-typography' => 'none',
                'placement' => 'top',
                'endpoint' => 0,
                'wpml_cf_preferences' => 0,
            ),
            array(
                'key' => 'field_5ddec20314fb1',
                'label' => 'Scheduled tweets',
                'name' => 'twitter_posts',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'wpml_cf_preferences' => 0,
                'wp-typography' => 'none',
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add tweet',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5de1528400d1b',
                        'label' => 'Tweet the meta description?',
                        'name' => 'post_meta_description',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                    ),
                    array(
                        'key' => 'field_5ddec20314fb3',
                        'label' => 'When should the tweet be published?',
                        'name' => 'date_and_time',
                        'type' => 'date_time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 0,
                        'wp-typography' => 'none',
                        'display_format' => 'Y-m-d H:i',
                        'return_format' => 'Y-m-d H:i',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_5ddec20314fb2',
                        'label' => 'Post',
                        'name' => 'content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5de1528400d1b',
                                    'operator' => '!=',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'wpml_cf_preferences' => 2,
                        'wp-typography' => 'none',
                        'default_value' => '',
                        'placeholder' => 'The meta description of the article will be posted if this field is left empty.',
                        'maxlength' => 256,
                        'rows' => 3,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5de15fada8657',
                        'label' => '',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'wp-typography' => 'none',
                        'message' => 'The post is published shortly after the set time. If no time is specified and the article is already published, the post is published shortly after the article is updated. If no time is specified and the article is a draft or scheduled for publication, the content is published shortly after the article is published. If the article isn\'t published or isn\'t public at the time of publishing the post, the post is never published.',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                        'wpml_cf_preferences' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;